@EvidenceAnalyzerAPI_HostAddress = http://localhost:5224

GET {{EvidenceAnalyzerAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{ImageAnalyzerAPI_HostAddress}}/ImageAnalyzer/
Accept: application/json

